export const actionTypes = {
    SET_ALL_CHARACTERS: "SET_ALL_CHARACTERS",
    SEARCHED_CHARACTER: "SEARCHED_CHARACTER",
    INC_PAGE_NUMBER: "INC_PAGE_NUMBER",
    DEC_PAGE_NUMBER: "DEC_PAGE_NUMBER",
    SET_STATUS: "SET_STATUS",
    SET_GENDER: "SET_GENDER",
    SET_SPECIES: "SET_SPECIES",
    SET_TYPE: "SET_TYPE"
}